- name: Deploy nginx site
  template:
    src: site.conf.j2
    dest: "/etc/nginx/sites-available/{{ project_name }}.conf"
  tags: ["deploy"]

- name: Remove default nginx site if present
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags: ["deploy"]

- name: Enable nginx site
  file:
    src: "/etc/nginx/sites-available/{{ project_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ project_name }}.conf"
    state: link
    force: true
  tags: ["deploy"]

- name: Test nginx config
  command: nginx -t
  tags: ["deploy"]

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  tags: ["deploy"]
